export enum apiStatusCode {
    AUTHOR_EXISTS = "AUTHOR_EXISTS",
    AUTHOR_DOES_NOT_EXIST = "AUTHOR_DOES_NOT_EXIST",
    SUCCESS = "SUCCESS",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    INVALID_INPUT = "INVALID_INPUT",
    BOOK_DOES_NOT_EXIST = "BOOK_DOES_NOT_EXIST"
}